# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

resources:
  pipelines:
    - pipeline: eshoponweb-ci
      source: Abdallah9858.eShopOnWeb
      trigger: true

variables:
  azureServiceConnection: 'azureconnection'
  resourceGroup: 'az400'
  location: 'West Europe'
  subscriptionId: '2312afc3-aa93-4bd9-96f6-c7a769252f5e'
  webAppName: 'az400-webapp'

stages:
- stage: Deploy
  displayName: Deploy eShopOnWeb

  jobs:
  - job: Deploy
    pool:
      name: Default

    steps:

    - download: eshoponweb-ci
      displayName: Download CI artifacts

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureServiceConnection)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/eshoponweb-ci/Bicep/webapp.bicep'
        overrideParameters: '-webAppName $(webAppName)'
        deploymentMode: 'Incremental'

    - task: AzureRmWebAppDeployment@4
      displayName: Deploy eShopOnWeb
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(azureServiceConnection)'
        appType: 'webApp'
        WebAppName: '$(webAppName)'
        packageForLinux: '$(Pipeline.Workspace)/eshoponweb-ci/Website/Web.zip'